config/routes.rb
Rails.application.routes.draw do
  get 'offline', to: 'home#offline'
  get 'manifest', to: 'home#manifest'
  root to: 'home#index'
  ActiveAdmin.routes(self)
  devise_for :users
  resources :notices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notice.rb
class Notice < ApplicationRecord
  has_one_attached :image
  enum notice_type: {notice: 'notice', intro: 'intro', event: 'event', ask: 'ask'}
  validates :notice_type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: {user: 'user', admin: 'admin'}, _prefix: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_admin!
    if !current_user&.role_admin?
      sign_out
      flash.alert = t('errors.not_admin')
      redirect_to new_user_session_path
    end
  end
  include Pundit
  after_action :verify_authorized, except: :index, unless: :framework_controller?
  after_action :verify_policy_scoped, only: :index, unless: :framework_controller?

  protected

  def framework_controller?
    devise_controller? || kind_of?(ActiveAdmin::BaseController)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_after_action :verify_policy_scoped
  skip_after_action :verify_authorized
  def index
    @notices = Notice.order(:created_at)
  end

  def manifest
  end

  def offline
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  skip_after_action :verify_authorized
  before_action :authenticate_user!
  
  def new
    @notice = Notice.new(notice_type: :notice)
  end
  
  def create
    Notice.create!(notice_params)
    redirect_to root_path
  end
  
  def notice_params
    params.require(:notice).permit(:notice_type, :message, :location, :contact, :image, :event_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def random_bg
    ['hsl(195,50%,95%)', 'hsl(195,0%,90%)', 'hsl(195,0%,100%)'].sample
  end
end

app/views/home/_ask.html.haml
.card.ask{style: "background-color: #{random_bg}"}
  .card-content
    %p= notice.message
    %p.contact= notice.contact

app/views/home/_event.html.haml
.card.event{style: "background-color: #{random_bg}"}
  .card-content
    %p= notice.message
    %p.date= notice.event_time.strftime('%A %-d %b, %I:%M%P')
    %p.location= notice.location
    %p.contact= notice.contact    

app/views/home/_intro.html.haml
.card.intro{style: "background-color: #{random_bg}"}
  .card-content
    %figure.image.is-128x128
      = image_tag notice.image, class: 'is-rounded'
    %p= notice.message

app/views/home/_notice.html.haml
.card.notice{style: "background-color: #{random_bg}"}
  .card-content
    %p= notice.message

app/views/home/index.html.haml
%section.section
  #notices{data: {controller: 'notices', target: 'notices.grid'}}
    - @notices.each do |n|
      = render n.notice_type, notice: n

app/views/home/offline.html.haml
%section.hero.is-light
  .hero-body
    .container
      %h1.title Offline

app/views/layouts/_messages.html.haml
- if flash[:notice] || flash[:alert]
  %section#messages{data: {controller: 'messages'}}
    - if flash[:notice]
      .notification.is-info.is-radiusless
        %button.delete{data: {action: 'messages#close'}}
        = flash[:notice]
    - if flash[:alert]
      .notification.is-danger.is-radiusless
        %button.delete{data: {action: 'messages#close'}}
        = flash[:alert]

app/views/layouts/_navbar.html.haml
%nav.navbar.is-primary{role: 'navigation', aria: {label: 'navigation'}, data: {controller: 'navbar'}}
  .navbar-brand
    = link_to root_path, class: 'navbar-item' do
      %b= t('product_name')
    %a.navbar-burger{role: 'button', aria: {label: 'menu', expanded: 'false'}, data: {target: 'navbar.burger', action: 'navbar#toggleMenu'}}
      - 3.times do
        %span{aria_hidden: true}
  .navbar-menu{data: {target: 'navbar.menu'}}
    .navbar-start
      = link_to 'New', new_notice_path, class: 'navbar-item'
    .navbar-end
      - if user_signed_in?
        - if current_user.role_admin?
          = link_to t('.admin'), admin_root_path, class: 'navbar-item', data: {turbolinks: false}
        = link_to t('devise.registrations.edit.title'), edit_user_registration_path, class: 'navbar-item'
        = link_to t('devise.sessions.destroy.title'), destroy_user_session_path, class: 'navbar-item', method: :delete
      - else
        = link_to t('devise.sessions.new.title'), new_user_session_path, class: 'navbar-item'
        = link_to t('devise.registrations.new.title'), new_user_registration_path, class: 'navbar-item'

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  %head
    = display_meta_tags site: t('product_name'), reverse: true, viewport: 'width=device-width, initial-scale=1.0', 'theme-color' => '#3d9970'
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag
    = favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png'
    = tag 'link', rel: 'manifest', href: manifest_path(format: :json)
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application', media: 'all'
  %body
    %header
      = render 'layouts/navbar'
      = render 'layouts/messages'
    %main= yield

app/views/notices/new.html.haml
%section.section{data: {controller: 'new-notice'}}
  .container
    %h1.title New notice
    %h2.subtitle{data: {target: 'new-notice.geo'}}
    = simple_form_for(@notice) do |f|
      = f.input :notice_type, as: :radio_buttons, collection: %i[notice event ask intro], include_blank: false, label: false, input_html: {data: {action: 'new-notice#changed'}}
      = f.input :message, as: :text
      = f.input :location, wrapper_html: {data: {target: 'new-notice.location'}}
      = f.input :contact, wrapper_html: {data: {target: 'new-notice.contact'}}
      = f.input :event_time, as: :string, wrapper_html: {data: {target: 'new-notice.time'}}, input_html: {data: {target: 'new-notice.datefield'}}
      = f.input :image, as: :file, wrapper_html: {data: {target: 'new-notice.image'}}
      .actions
        = f.button :submit